name: start_frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  quiver: ^3.2.1
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_colorpicker: ^1.0.3
  share_plus: ^7.1.0
  table_calendar: ^3.0.9
  flutter_spinkit: ^5.2.0
  number_slide_animation: ^0.2.1
  flutter_slidable: ^3.0.0
  firebase_storage: ^11.2.7
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Thin.otf
          weight: 700

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/intro/
    - assets/icons/
    - assets/icons/brands/
    - assets/imports/
    - assets/imports/classes/
    - assets/imports/games/
    - assets/imports/profile/
    - assets/imports/meetup/
