name: start_app_frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  redux: ^5.0.0
  flutter_redux: ^0.10.0
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  image_picker: ^0.8.6
  google_sign_in: ^5.4.2
  quiver: ^3.1.0
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_colorpicker: ^1.0.3
  share_plus: ^6.3.0
  intl: ^0.17.0
  table_calendar: ^3.0.8
  flutter_spinkit: ^5.1.0
  number_slide_animation: ^0.2.1
  flutter_slidable: ^2.0.0
  firebase_storage: ^11.0.6
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
